### ISSUE TITLE
Generate custom podling logo for the project

### ISSUE THREAD

**Issue by jnioche** [apache/incubator-stormcrawler-site#4]
See https://incubator.apache.org/guides/press-kit.html

**Comment by rzo1** [comment]
Do we have a vector graphic or alike of the original logo (instead of only the PNG) ?

**Comment by rzo1** [comment]
Might be the `.ai` file? (adobe indesign)

**Comment by jnioche** [comment]
https://github.com/apache/incubator-stormcrawler-site/blob/main/img/Logo.ai

**Comment by rzo1** [comment]
Do we know someone with Inkscape or Adobe Illustrator skills @jnioche @sebastian-nagel @tballison @michaeldinzinger
